<%
'::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
'::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
'<> Copyright (C) 2005-2006 Dogg Software All Rights Reserved
'<>
'<> By using this program, you are agreeing to the terms of the
'<> SkyPortal End-User License Agreement.
'<>
'<> All copyright notices regarding SkyPortal must remain 
'<> intact in the scripts and in the outputted HTML.
'<> The "powered by" text/logo with a link back to 
'<> http://www.SkyPortal.net in the footer of the pages MUST
'<> remain visible when the pages are viewed on the internet or intranet.
'<>
'<> Support can be obtained from support forums at:
'<> http://www.SkyPortal.net
'::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
'::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::


'set my_Conn= Server.CreateObject("ADODB.Connection")
'my_Conn.Open strConnString

strDBNTFUserName = chkString(Request.Form("Name"),"display")
tempArr = split(strWebMaster, ",")
strSiteOwner = tempArr(0)

':: check login status - member or guest
chkLoginStatus()

':: populate member groups array
bldArrUserGroup()

':: build array for app access
bldArrAppAccess()

if trim(curpagetype) <> "" and trim(curpagetype) <> "home" and trim(curpagetype) <> "core" then
    if not chkApp(curpagetype,"USERS") then
	  'closeAndGo("blank.asp")
	end if
end if
%>
<!--#include file="includes/inc_ipgate.asp" -->
<!--#include file="includes/inc_theme.asp" -->
<% 
getPageSkin(arrGroups(0,0))

If (mLev = 0 and strLockDown <> 0 and lockDownOverRide <> "1") or strLockDown = "" Then
  if strAuthType = "nt" then 
'do nothing 
  else %>
	<html>
	<head>
	<%spThemeHeader_style()%>
	</head>
    <body>
	<br><br><br><br><center><b><%=txtMustBMember1%><br><%=txtToPartic%>.</b></center><br><br><br><br>
	<p align="center"><a href="JavaScript:onClick= window.close();"><%= txtCloseWin %></a></p>
	</body>
	</html>
    <%
	closeAndGo("stop")
  end if
end if
 %>
<!-- This page is generated by SkyPortal.net-->
<html>

<head>
<title><% =strSiteTitle %></title>
<%'** START - REMOVAL OR MODIFICATION OF THIS CODE WILL VIOLATE THE SkyPortal LICENSE AGREEMENT%>
<meta name="COPYRIGHT" content="Portal code is Copyright (C)2005-2006 Tom Nance (SkyDogg) All Rights Reserved" />
<%'** END   - REMOVAL OR MODIFICATION OF THIS CODE WILL VIOLATE THE SkyPortal LICENSE AGREEMENT%>
<script language="JavaScript" type="text/JavaScript">
<!--
var js_welcome = ""
 var js_none = "<%= txtNone %>";
 var js_member = "<%= txtMember %>";
 var js_admin = "<%= txtAdmin %>";

 // preload min-max images
  var mmImages = new Array(4);
  mmImages[0] = "Themes/<%= strTheme %>/icon_max.gif";
  mmImages[1] = "Themes/<%= strTheme %>/icon_min.gif";
  mmImages[2] = "Themes/<%= strTheme %>/icon_max1.gif";
  mmImages[3] = "Themes/<%= strTheme %>/icon_min1.gif";
// -->
</script>
<script language="javascript" src="<%= strHomeURL %>includes/scripts/core.js"></script>
<% if (curpagetype = "pm" and iMode = 2) and not thispage = "monitor" then %>
<script language="javascript" src="<%= strHomeURL %>includes/scripts/menu_com.js"></script>
<% end if %>
<% if hasEditor = true and editorType = "tinymce" and strAllowHtml = 1 then %>
<script language="javascript" type="text/javascript" src="tiny_mce/tiny_mce.js"></script>
<% End If %>
<script language="JavaScript" type="text/JavaScript">
<!--
var popwin = null;
function popUpWind(mypage,myname,w,h,scr,resiz){
LeftPosition = (screen.width) ? (screen.width-w)/2 : 0;
TopPosition = (screen.height) ? (screen.height-h)/2 : 0;
settings =
'height='+h+',width='+w+',top='+TopPosition+',left='+LeftPosition+',scrollbars='+scr+',toolbar=no,resizable='+resiz+',menubar=no'
popwin = window.open(mypage,myname,settings)
}
function autoReload() {
	document.ReloadFrm.submit()
}
function SetLastDate() {
	document.LastDateFrm.submit()
}
function openWindow3(url) {
  popupWin = window.open(url,'pop_col','width=400,height=450,scrollbars=yes')
}

function shoGlow() {
var newGlow = document.forms.Form1.strGlowColor.value;
document.all['glowname'].style.filter='glow(color:'+newGlow+',strength:4); width:100%';
}
function shoText() {
var newGlow = document.forms.Form1.strTxColor.value;
document.all['glowname'].color=newGlow;
}
<% If strAllowHtml <> 1 Then %>
function openWindowPM(url) {
  popupWin = window.open(url,'pm_pop_send','resizable,width=590,height=510,top=35,left=120,scrollbars=yes');
}
<% Else %>
function openWindowPM(url) {
  popupWin = window.open(url,'pm_pop_send','resizable,width=635,height=550,top=30,left=120,scrollbars=yes');
}
<% End If %>
// -->
</script>
<%spThemeHeader_style()%>
<!--#include file="includes/inc_editor.asp"-->
</head>
<% if thispage = "monitor" then
  spThemeShortBodyTag = ""
end if %>
<BODY leftmargin="0" topmargin="0" marginwidth="0" marginheight="0" <%=spThemeShortBodyTag%>>
<table class="spTheme" width="100%" height="100%" cellpadding="0" cellspacing="0">
  <tr>
    <td align="center" valign="top">
    <div align=center><center>